export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED'
export const FETCH_USER_CANCELLED = 'FETCH_USER_CANCELLED'
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED'
